### ISSUE TITLE
ホワイトボックステスト vol.1

### ISSUE THREAD

**Issue by laco0416** [asada0701/MyWebServer#36]
ひたすら書いてく

**Comment by laco0416** [comment]
- `./gradlew run` するとサーバーが立ち上がったらしいがどのポートで立ち上がったのか何の情報もないので動かせません〜

**Comment by asada0701** [comment]
お願いします。

**Comment by laco0416** [comment]
要求仕様

```
"普通のWebサーバ"を作る。

静的リソースの配信ができ、最新のChromeで閲覧することができる
Firefoxでも少し確認するとなお良い
HTML, CSS, JavaScript, jpeg, png, gifを組み合わせたWebページを表示できること
"普通"が指す範囲を検討し、実装する
200, 404 など各種ステータスコードのサポートがあること
その他色々
```

**Comment by laco0416** [comment]
`localhost:8080` にアクセス。

期待する挙動: `index.html` にあるHTMLが表示される

まあよさそう

> HTML, CSS, JavaScript, jpeg, png, gifを組み合わせたWebページを表示できること

pngとgifは使ってなかった。

**Comment by laco0416** [comment]
最初から入ってるファイルに関しては問題なく配信できてそう

**Comment by laco0416** [comment]
`/music/sample.mp3` もちゃんと配信されて落ちてきた

**Comment by laco0416** [comment]
それぞれContent-Typeも正しそう。

**Comment by laco0416** [comment]
- 拡張子のないリクエストでサーバーが落ちる

`localhost:8080/bar` にアクセスすると

```
Exception in thread "Thread-0" java.lang.ArrayIndexOutOfBoundsException: 1
        at jp.co.topgate.asada.web.ResourceFile.<init>(ResourceFile.java:38)
        at jp.co.topgate.asada.web.HttpHandler.<init>(HttpHandler.java:46)
        at jp.co.topgate.asada.web.Server.run(Server.java:69)
```

**Comment by laco0416** [comment]
- 存在するファイルに対する拡張子のないリクエストでサーバーが落ちる
- `hoge` ファイルを追加したうえで localhost:8080/hoge にアクセスすると

Exception in thread "Thread-0" java.lang.ArrayIndexOutOfBoundsException: 1
        at jp.co.topgate.asada.web.ResourceFile.<init>(ResourceFile.java:38)
        at jp.co.topgate.asada.web.HttpHandler.<init>(HttpHandler.java:46)
        at jp.co.topgate.asada.web.Server.run(Server.java:69)

**Comment by laco0416** [comment]
- `/foo/` にアクセスしたときに `/foo/index.html` が配信されずサーバーが落ちる

`/` にアクセスしたときの `/index.html` の配信と一貫性がない

```
Exception in thread "Thread-0" java.lang.ArrayIndexOutOfBoundsException: 1
        at jp.co.topgate.asada.web.ResourceFile.<init>(ResourceFile.java:38)
        at jp.co.topgate.asada.web.HttpHandler.<init>(HttpHandler.java:46)
        at jp.co.topgate.asada.web.Server.run(Server.java:69)
```

**Comment by laco0416** [comment]
リソースパスの処理がガバガバっぽいな？

**Comment by laco0416** [comment]
- 名前に日本語を含むファイルが配信できていない

`寿司.txt` を用意しても `localhost:8080/寿司.txt` でアクセスできない

**Comment by asada0701** [comment]
かなりガタガタですね自分でも笑ってしまいました。修正していきたいと思います。

**Comment by laco0416** [comment]
- 巨大なファイルの配信中に別のクライアントからのリクエストも止まる

2.2GBのファイルを落としながら別のタブでindex.htmlを表示しようとしてもレスポンスが返ってこない。

**Comment by laco0416** [comment]
とりあえず以上！

**Comment by vvakame** [comment]
> 巨大なファイルの配信中に別のクライアントからのリクエストも止まる

これはまーいいかな〜〜という気がする(最終的に表示されればよい

**Comment by asada0701** [comment]
*[OK]ポート番号の情報がない。
*[OK]pngとgifは使ってなかった。
*[OK]存在しないファイルに対する拡張子のないリクエストでサーバーが落ちる
*[OK]存在するファイルに対する拡張子のないリクエストでサーバーが落ちる
*[OK]/ にアクセスしたときの /index.html の配信と一貫性がない
仕様を変更、どの/foo/にアクセスした場合は/foo/index.htmlを探す。
*[OK]名前に日本語を含むファイルが配信できていない
*[未実装]巨大なファイルの配信中に別のクライアントからのリクエストも止まる
仕様を変更、リクエストは同時に処理できません。最終的に表示できました。

**Comment by asada0701** [comment]
* [ ] ポートの情報がどこにもない

**Comment by asada0701** [comment]
* [ ] pngとgifは使ってなかった。
* [ ] 存在しないファイルに対する拡張子のないリクエストでサーバーが落ちる
* [ ] 存在するファイルに対する拡張子のないリクエストでサーバーが落ちる
* [ ] / にアクセスしたときの /index.html の配信と一貫性がない
仕様を変更、どの/foo/にアクセスした場合は/foo/index.htmlを探す。
* [ ] 名前に日本語を含むファイルが配信できていない
* [ ] 巨大なファイルの配信中に別のクライアントからのリクエストも止まる
仕様を変更、リクエストは同時に処理できません。最終的に表示できました。

**Comment by laco0416** [comment]
- すべての画像は二次利用が認められた著作権フリーな物ですか？

**Comment by laco0416** [comment]
- ファイル名の先頭に `.` が付いたHTMLファイルが表示できない

`.ignored.html` を作成するとファイルのダウンロードが始まり、HTMLが表示されない

**Comment by laco0416** [comment]
- `http://localhost:8080/?foo=bar` がNotFoundになる

**Comment by laco0416** [comment]
- Shift-JIS形式で保存したHTMLファイルが文字化けする

常にContent-Typeのencofingがutf-8なのでこうなる

![image](https://cloud.githubusercontent.com/assets/1529180/25367654/07e1e1a2-29b2-11e7-8c41-1ca0c9e45021.png)

**Comment by laco0416** [comment]
以上！

**Comment by asada0701** [comment]
* [ ] すべての画像は二次利用が認められた著作権フリーな物ですか？
* [ ] ファイル名の先頭に . が付いたHTMLファイルが表示できない
* [ ] http://localhost:8080/?foo=bar がNotFoundになる
* [ ] Shift-JIS形式で保存したHTMLファイルが文字化けする

**Comment by vvakame** [comment]
Shift-JISはまぁいいかな〜〜〜という気もする。

**Comment by vvakame** [comment]
画像、フリーはフリーでも出典元表記とかないといけない場合があるので気をつけよう(ライセンス条項をよく確認する

**Comment by asada0701** [comment]
ライセンスを読んだ結果、よく分からない場合は使用をしない方がよろしいですよね？
https://gifmagazine.net
こちらのサイトで画像を拝借しようかと思い、やめました。

**Comment by asada0701** [comment]
文字コードの指定は仕様に書くようにします。

**Comment by laco0416** [comment]
著作権に関しては、ライセンス表示や時効によって明らかに利用可能でない場合は基本的に常にNGです。また、ライセンスがない、というのは許可されていない、と同じです。

**Comment by laco0416** [comment]
サーバーはこれでよかろう！ホワイトボックステストはクリアとします。

**Comment by asada0701** [comment]
ありがとうございます。
著作権に関して理解が足りてませんでした。調べてみます。
