### ISSUE TITLE
コードレビュー

### ISSUE THREAD

**Issue by laco0416** [asada0701/MyWebServer#67]
- パッケージとその中にあるソースコードが変。appパッケージが掲示板機能を司っているならHandlerやStatusLineはwebパッケージにあるべきだし、全体をappとしたいならStaticHandlerはappの下にあるべき 
- 各所にある `EditHtmlList ehl;` みたいな変数名は省略しすぎ Javaではあまり好まれない

## App.java

- `Choices` と `choices` は `ServerCommand` なのではという気がする あと`choice` でいいのでは
- `Scanner scan` は `Scanner scanner`
- `HtmlEditor he`は変数名を省略する必要ないので `htmlEditor` と書いたほうがよい
- `isSelect` は名前がおかしい気がするし、これはChoices側にstaticメソッドで書くべき内容では？
- `controlServer`のswitch文でfall throughが発生するようになっているけどこれはやめたほうがいい

## Server.java

- サーバーを起動するポート番号がServerのprivate staticで管理されているのは責務が違う Serverは任意のポートにソケットを開くのが仕事なので、App側からポート番号を受け取って、そのポートで起動するほうがいい
- `socket`と`serverSocker`というのが対称性がないので、`socket`は`clientSocket`のほうがわかりやすそう
- InputStreamをHandler.getHandlerに渡して、戻り値のHandlerから`StatusLine sl`を受け取っているけど、`sl`は次のメソッドでまたHandlerに渡しているんだからこの処理は不要なのでは？Server側で`sl`使ってない

## Handler.java

- コンストラクタでInputStreamを受け取るのはあんまりイケてない気がする。RequestMessageへの変換まではServerの仕事で、RequestMessageを元にHandlerが選択されるべきかな

## HtmlEditor.java

- `allInitialization()` は`initializeAll()` あるいは `resetAllFiles()` みたいな名前のはず 動詞形

## ProgramBoardHandler.java

- GETのときとPOSTのときの対称性がない `doPost()` を用意したならGETも `doGet` でやるべき
- `DELETE1` と `DELETE2`にちゃんと名前をつける
- `CONTRIBITION`? 貢献？

----

全体的に名前が少し雑なので見直し

**Comment by asada0701** [comment]
- [ ] パッケージとその中にあるソースコードが変。appパッケージが掲示板機能を司っているならHandlerやStatusLineはwebパッケージにあるべきだし、全体をappとしたいならStaticHandlerはappの下にあるべき
- [ ] 各所にある EditHtmlList ehl; みたいな変数名は省略しすぎ Javaではあまり好まれない

**Comment by asada0701** [comment]
- [ ] Choices と choices は ServerCommand なのではという気がする あとchoice でいいのでは
- [ ] Scanner scan は Scanner scanner
- [ ] HtmlEditor heは変数名を省略する必要ないので htmlEditor と書いたほうがよい
- [ ] isSelect は名前がおかしい気がするし、これはChoices側にstaticメソッドで書くべき内容では？
- [ ] controlServerのswitch文でfall throughが発生するようになっているけどこれはやめたほうがいい

**Comment by asada0701** [comment]
- [ ] サーバーを起動するポート番号がServerのprivate staticで管理されているのは責務が違う Serverは任意のポートにソケットを開くのが仕事なので、App側からポート番号を受け取って、そのポートで起動するほうがいい
- [ ] socketとserverSockerというのが対称性がないので、socketはclientSocketのほうがわかりやすそう
- [ ] InputStreamをHandler.getHandlerに渡して、戻り値のHandlerからStatusLine slを受け取っているけど、slは次のメソッドでまたHandlerに渡しているんだからこの処理は不要なのでは？Server側でsl使ってない

**Comment by asada0701** [comment]
- [ ] コンストラクタでInputStreamを受け取るのはあんまりイケてない気がする。RequestMessageへの変換まではServerの仕事で、RequestMessageを元にHandlerが選択されるべきかな

**Comment by asada0701** [comment]
- [ ] allInitialization() はinitializeAll() あるいは resetAllFiles() みたいな名前のはず 動詞形

**Comment by asada0701** [comment]
- [ ] GETのときとPOSTのときの対称性がない doPost() を用意したならGETも doGet でやるべき
- [ ] DELETE1 と DELETE2にちゃんと名前をつける
- [ ] CONTRIBITION? 貢献？

**Comment by asada0701** [comment]
- [ ] 全体的に名前が少し雑なので見直し

**Comment by laco0416** [comment]
## App.java

- `ServerCommand.contains`は3つの条件をOR取っているけど、これは`getServerCommand`と同じように`values()`で全件走査すべきでは？
- ポート番号はApp.javaから受け取るべきというのは、とりあえず定数の置き場所がApp側にあるべきという話だったけど、手入力できるようになってて驚いた ただしこうするなら空文字列や数字じゃないものを渡されたときに8080をデフォルトで使うようになってればより良いと思う 面倒なら8080固定に戻してもよい
- `Server server = setPortNumber();` という1文のおかしさ

## Server.java

- handlerのメソッド呼び出しが冗長に思う

```
handler.doRequestProcess();
handler.doResponseProcess(clientSocket.getOutputStream());
```

という2行があるけど、こういう設計だと`doResponseProcess`をうっかり先に呼び出したときの挙動が保証できない。間違いにくいインターフェースが良いインターフェースなので、この場合は単純に`handle`メソッドがひとつあれば良い気がする。次のようなイメージ

```
handler.handleRequest(clientSocket.getOutputStream());
```

`doRequestProcess`と`doResponseProcess`はprivateメソッドとして処理の分割のために存在していればいいけど、Handlerクラスを使う側にとってその分割が必要かどうかも考えてみましょう

## RequestMessageParser.java

- クラス名でわかってるのでメソッド名は `parse`でよい

## ResponseMessage.java

- `returnResponse`はreturnと言っているのにvoidを返す この場合は`write`が正しそう

## DoPostException.java

- POSTかどうかで例外を区別する必要ある？Handlerが発生させる例外というくくりでよいのでは？

## HtmlInitializeException.java

- IOExceptionの情報を捨てずに、causeを渡すようにしましょう。RuntimeExceptionのコンストラクタのオーバーロードを調べること

## AppTest.java

- 文字列リテラルでテストするより、`controlServer`はStringの定数を返すようにしていたほうがテストしっやすいですね
- その戻り値も例えば`ServerState`みたいなenumで扱えば、もっと扱いやすいですね
- 文字列に意味を与えるのはメンテナンス性を落とすのでなるべく避けましょう

## HandlerTest.java

- `WebAppHandlerが返されるテスト` ProgramBoard

## ServerCommandTest.java

- 空文字列と、正常系しかテストされてなくて、テストするなら異常な入力(`"9"`とか)もやらないと効果が薄い

## ContentTypeTest.java

- 同上。異常系のテストを増やそう


----
だいたい良い。文字列リテラルに頼りすぎているところがあるので、enum化やクラス化、定数化など使ってみましょう。

リクエストのシミュレーションするテストで、レスポンスのHTMLを頑張ってJava上で組み立ててテストしているけど、リクエストと同じようにレスポンスも想定されるものをファイルとして置いておいて、それをテストで読み込んで使ってもよいですよ

**Comment by asada0701** [comment]
- [ ] ServerCommand.containsは3つの条件をOR取っているけど、これはgetServerCommandと同じようにvalues()で全件走査すべきでは？
- [ ] ポート番号はApp.javaから受け取るべきというのは、とりあえず定数の置き場所がApp側にあるべきという話だったけど、手入力できるようになってて驚いた ただしこうするなら空文字列や数字じゃないものを渡されたときに8080をデフォルトで使うようになってればより良いと思う 面倒なら8080固定に戻してもよい
- [ ] Server server = setPortNumber(); という1文のおかしさ

**Comment by asada0701** [comment]
- [ ] handlerのメソッド呼び出しが冗長に思う

**Comment by asada0701** [comment]
- [ ] クラス名でわかってるのでメソッド名は parseでよい

**Comment by asada0701** [comment]
- [ ] returnResponseはreturnと言っているのにvoidを返す この場合はwriteが正しそう
DoPostException.java

- [ ] POSTかどうかで例外を区別する必要ある？Handlerが発生させる例外というくくりでよいのでは？
HtmlInitializeException.java

- [ ] IOExceptionの情報を捨てずに、causeを渡すようにしましょう。RuntimeExceptionのコンストラクタのオーバーロードを調べること

**Comment by asada0701** [comment]
- [ ] 文字列リテラルでテストするより、controlServerはStringの定数を返すようにしていたほうがテストしっやすいですね
- [ ] その戻り値も例えばServerStateみたいなenumで扱えば、もっと扱いやすいですね
- [ ] 文字列に意味を与えるのはメンテナンス性を落とすのでなるべく避けましょう

**Comment by asada0701** [comment]
- [ ] WebAppHandlerが返されるテスト ProgramBoard

- [ ] 空文字列と、正常系しかテストされてなくて、テストするなら異常な入力("9"とか)もやらないと効果が薄い

- [ ] 同上。異常系のテストを増やそう

**Comment by asada0701** [comment]
質問です。
ResponseMessageクラスの責務はレスポンスメッセージを生成することであって、
clientSocketのoutputStreamにレスポンスメッセージを書き込むのはServerの責務の気がしてきたのですが
どうでしょうか？

**Comment by laco0416** [comment]
いい感覚 やってみていいと思いますが、問題は ResponseMessage をどうやって書き込むのか(実際は文字列化して、byte[]にして、writeする)の方法は誰の責務か、というところ
ServerはResponseMessageがどのようにバイナリ化できるのかを知るべきか？という話で、今回の場合はResponseMessageに `writeToOutputStream(outputStream)` がベターな責務の分割だと思います。

**Comment by asada0701** [comment]
- [ ] テストの見直し

**Comment by laco0416** [comment]
## Server.java

- ちょっと惜しい。口頭で説明したい

## RequestMessageParserTest.java

- `RequestMessage sut` の sutって何かわからなかった
- 各所に`sut`出てくるけどなんか本とかWebで紹介されてたもの？あんまり一般的じゃないと思う

---

だいたいいい。今回のレビューに対応したらホワイトボックステストに入ってよい
