### ISSUE TITLE
ホワイトボックステスト

### ISSUE THREAD

**Issue by laco0416** [asada0701/MyWebServer#85]
## 1回目

- `./gradlew run` に失敗する

`Error: Could not find or load main class jp.co.topgate.asada.web.App`

おしまい

**Comment by asada0701** [comment]
すみません。修正して動作確認しました。

**Comment by laco0416** [comment]
## 2回目

- `http://localhost:8080/program/board/` にアクセスして、最初の投稿をしたあと、ブラウザをリロードすると同じ内容が投稿され続ける

**Comment by laco0416** [comment]
挙動はいいと思う。課題に求められてる仕様は満たしている
見た目の問題がいくつかあるので暇になったら直してみて

- 投稿ボタン
![image](https://cloud.githubusercontent.com/assets/1529180/26477590/95208598-4201-11e7-86c3-f82a47cee179.png)

- 200文字投げるとテーブルがすごく横に長くなる 横幅はウィンドウ幅にして折り返してほしい
