### ISSUE TITLE
掲示板作る課題のコードレビュー by vv

### ISSUE THREAD

**Issue by vvakame** [asada0701/MyWebServer#91]
* コミットグラフが良くない形になってるところがまたあってよくない
* `ModelController.setMessageList(CsvHelper.readMessage());` が Main クラスにあるのが微妙
  * 雑な指標として `jp.co.topgate.asada.web` パッケージに属するクラスが `jp.co.topgate.asada.web.model` とか `jp.co.topgate.asada.web.program.board` の要素をimportしているのは役割の分割がおかしいのではないかと思う
  * 上の指標に厳密に従うとルーティング周り( `/program/board/` にアクセスした時どのクラスが処理するの？ )の記述に困難が生じる(不可能ではない)ので厳密にやりすぎる必要はないが…
* Messageクラスは `jp.co.topgate.asada.web.program.board` の持ち物であるべきだと思うんだけど別packageに分かれてるのは何故だろう？
  * `jp.co.topgate.asada.web.program.board.model` とかだと理解できる
* `HtmlEditor htmlEditor` という変数を作ってから使うまでが長すぎる
  * 変数の生存期間はなるべく短いほうがよい
  * バグを防ぐため
  * 可読性を増すため
* 正規の手段でサーバを止めなかった時にCSVが保存されないのはなんか一般的じゃない気がする…
  * メッセージをポストして処理が成功したらそれは既に永続化されている というのが一般的だと思う
* RequestMessageParser#parse について
  * `byte[] messageBody = readMessageBody(bis, contentLength);` は動画とかアップロードされると厳しいことになるのであまりよくない気がするなー(何回か言ってる気がする
* RequestMessageParser#readMessageBody について
  * 何やってるのかわかりづらい
  * コメントをガッツリ書くか、リファクタリングしたほうがいいと思う
  * ヘッダ行は既に処理済みなので何バイト読み飛ばせばいいかは既知なのでは？
* `REQUEST_MESSAGE_CARRIAGE_RETURN = 13`
  * `REQUEST_MESSAGE_CARRIAGE_RETURN = '\r'` とかでいいのでは(charとintは互換性がある(たしか
* Handler#getHandler について
  * 後で使わないかもしれないけど `new StaticHandler(requestMessage);` するのは無駄では…
    * パッと見、副作用があるかないかわからないので不審な気持ちになる
  * `PROGRAM_BOARD("/program/board/", "/2/");` とするのが謎なんだけど素直に `/program/board/` に置けばいいのでは…？
    * 他の指摘でもそうなんだけど、"狙いが想像できない謎の工夫"があると良くないみたいな話
    * 表からアクセスできないようにしたいのかなと思ったけど http://localhost:8080/2/ で普通にアクセスできるし
* runして、サーバ終了させるときに `END: END` って書いてあったので END って入力したら弾かれたでござる
* ファイルパスの連結にStringの + 使ってる例が多いけど別のなんかよい方法あった気がする
  * `"hoge/" + "./piyo.html" みたいな事しても困らない奴 `new File(dirPath, fileName).getPath()` 的な…？
* `InvalidChar` というとデータとしてぶっ壊れている文字 みたいな印象をうける
  * `UnsafeChar` とかかなぁ…？
  * Invalidではない感がある
* `HtmlEditor` が何なのかわからなさがすごいのでもっとガッツリJavadoc書いてほしい
* コメントを投稿した人の他のコメントを見る でURLが変わらないのがあまり現代っぽくない
  * URLがshareできたほうがよいとかそういう
* `ProgramBoardHandler#handleRequest` について
  * `requestMessage.setUri(newUri);` できてしまうのはおかしいのでは…
* `StatusLine` がenumになっていて未知のステータスコードを返せないのあまりよくないと思う
  * https://japan.cnet.com/article/35075328/ たまに増えたりする

総評として、"分かってないと読めない"コードになっている箇所が多いように思う。
初見でも読めるコードを目指してみましょう。

**Comment by asada0701** [comment]
- [ ] コミットグラフが良くない形になってるところがまたあってよくない
- [ ] ModelController.setMessageList(CsvHelper.readMessage()); が Main クラスにあるのが微妙
- [ ] Messageクラスは jp.co.topgate.asada.web.program.board の持ち物であるべきだと思うんだけど別
- [ ] HtmlEditor htmlEditor という変数を作ってから使うまでが長すぎる
- [ ] 正規の手段でサーバを止めなかった時にCSVが保存されないのはなんか一般的じゃない気がする…
- [ ] メッセージをポストして処理が成功したらそれは既に永続化されている というのが一般的だと思う
- [ ] RequestMessageParser#parse について
- [ ] RequestMessageParser#readMessageBody について
- [ ] REQUEST_MESSAGE_CARRIAGE_RETURN = 13
- [ ] Handler#getHandler について
- [ ] runして、サーバ終了させるときに END: END って書いてあったので END って入力したら弾かれたでござる
- [ ] ファイルパスの連結にStringの + 使ってる例が多いけど別のなんかよい方法あった気がする
- [ ] InvalidChar というとデータとしてぶっ壊れている文字 みたいな印象をうける
- [ ] HtmlEditor が何なのかわからなさがすごいのでもっとガッツリJavadoc書いてほしい
- [ ] コメントを投稿した人の他のコメントを見る でURLが変わらないのがあまり現代っぽくない
- [ ] ProgramBoardHandler#handleRequest について
- [ ] StatusLine がenumになっていて未知のステータスコードを返せないのあまりよくないと思う

**Comment by vvakame** [comment]
反映終わったら自分でCloseしてほしい。

**Comment by vvakame** [comment]
せっかくだから再利用しようかな。

**Comment by asada0701** [comment]
次からはCloseするよう気をつけます。

**Comment by vvakame** [comment]
なんかわりと現状でもそれなりに整ってるのでは。みたいな気持ち。

ある意味重箱の隅的な指摘。対応せずにこのまま動作確認テストに行きます！とかでもOK。

* ResponseMessage#getOutputStream
  * `if (headerField.size() > 0) {` は不要なのでは？
  * これ系のメソッドを複数回呼ぶとレスポンスをぶっ壊せそう
    * get*** とかは特に副作用がない(ように見える)ことが期待されていると思う
* ProgramBoardHandler と ModelController と CsvHelper の責任分割が怪しい
  * 少なくとも ModelControllerもCsvHelperも結局Messageを扱っているのでは…？
* RequestMessageParser#changeUriToWelcomePage
   * `/` で終わっている時に勝手に index.html を補うのは一般的にアプリ製作者の意図する挙動じゃないと思うな
  * RequestMessage からは生データに近いものが取れてほしいと期待する
* ProgramBoardHandler#doGet
  * `throw new IllegalRequestException` のような、標準的なフローに例外を使うのはよくない
    * 例外の意味を辞書で引く
  * Javaは多値が返せないが、だからといって例外で値を伝えるのは間違った設計である
  * 普通に responseMessage.setStatusCode(BAD_REQUEST); 的なコード書かせるんじゃあかんの

**Comment by asada0701** [comment]
- [ ] ResponseMessage#getOutputStream
if (headerField.size() > 0) { は不要なのでは？
これ系のメソッドを複数回呼ぶとレスポンスをぶっ壊せそう
get*** とかは特に副作用がない(ように見える)ことが期待されていると思う
- [ ] ProgramBoardHandler と ModelController と CsvHelper の責任分割が怪しい
少なくとも ModelControllerもCsvHelperも結局Messageを扱っているのでは…？
- [ ] RequestMessageParser#changeUriToWelcomePage
/ で終わっている時に勝手に index.html を補うのは一般的にアプリ製作者の意図する挙動じゃないと思うな
RequestMessage からは生データに近いものが取れてほしいと期待する
- [ ] ProgramBoardHandler#doGet
throw new IllegalRequestException のような、標準的なフローに例外を使うのはよくない
例外の意味を辞書で引く
Javaは多値が返せないが、だからといって例外で値を伝えるのは間違った設計である
普通に responseMessage.setStatusCode(BAD_REQUEST); 的なコード書かせるんじゃあかんの
