### ISSUE TITLE
掲示板課題 ホワイトボックステスト by vv

### ISSUE THREAD

**Issue by vvakame** [asada0701/MyWebServer#98]
## 公開を意図していないフォルダにアクセス可能なセキュリティ上の問題

```
$ telnet localhost 8080
Trying ::1...
Connected to localhost.
Escape character is '^]'.
GET /../../../../../../.ssh/id_rsa.pub HTTP/1.1

HTTP/1.1 200 OK
Content-Type: application/octet-stream
Content-Length: 402

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQChpaj57SNQLE2dZG1tK5TddQpoaEw7pXFPxx0gwIG/GnNZeFuPJGu6o2shV6n1SgKQAbuYhpdcf1iACY+GFs+62E08fZ5J/wSbRvGsQkaBkIHEy0ZU2+obODbt5UysbGRc4P7WZa45Hteav/wHZN0cNt4oDKn6zACFK7joGTPwHq2185ZePKbffnycGxOHT6KWFuPs+GOz8Z6IXB9Cykyn1+IDV495d8VrCa/sXHTijhUWlP+SFSUJsqGATbiAng/nwYpP2UzWiUYJGH5cIDs8eV9ipF4kOBZvH28EfIHAUObp+p7Fkmtf0dWNcIEvFRCWR1P3N5NfyRpwJ7HE0N99 vvakame@dieter.local
Connection closed by foreign host.
```

任意のファイルにアクセスできるので秘密鍵(この例は公開鍵だけど)とかを抜き取ったりもできる

## リンクである事が適切なパターンでボタンが用いられている場合がある

他のコメントも見る的なやつとかtopに戻る的なやつとか。
これらは普通にリンクでGETで良いでしょう。

## パスワードを間違えた時に何らかのエラー表示がほしい

動いてるのか不安になる
Bad Request系の時に適切な表示を行うパスが全体的に存在していない？

## 存在しないユーザ名を表示しようとするとBad Requestになる

http://localhost:8080/program/board/search.html?param=search&name=hoge
のname部分を適当に変更してアクセスするとBad Requestになる。
期待値としてはメッセージが1つもない画面が出てくるとか、何か普通にアプリケーションの正規のレスポンスぽいものが出てくること。

## 存在しないparamを指定すると404になる

http://localhost:8080/program/board/search.html?param=test&name=dsa
同上
URLの構成上は search.html という静的なファイルにアクセスしていて、それに対してパラメータが変わると404が返ってくるというのはちょっとおかしい。
そういう意味では静的なファイルにアクセスしているっぽいURLなのに動的なコンテンツが返ってくるのはあまり現代だと見かけないな…(よくない気もする

**Comment by asada0701** [comment]
- [ ] 公開を意図していないフォルダにアクセス可能なセキュリティ上の問題
- [ ] リンクである事が適切なパターンでボタンが用いられている場合がある
- [ ] パスワードを間違えた時に何らかのエラー表示がほしい
- [ ] 存在しないユーザ名を表示しようとするとBad Requestになる
- [ ] 存在しないparamを指定すると404になる
