### ISSUE TITLE
ホワイトボックステスト laco

### ISSUE THREAD

**Issue by laco0416** [asada0701/MyWebServer#99]
#98 に引き続き

### レスポンスの一貫性

- `http://localhost:8080/program/board/search.html?param=search&name=`  => Bad Request (空文字列で検索した結果を返すべきでは？)
- `http://localhost:8080/program/board/search.html?param=search` => Bad Request (まあよい)
- `http://localhost:8080/program/board/search.html?name=a` => 200 (なぜかエラーにならないしリダイレクトもされない)
- `http://localhost:8080/program/board/search.html?param=bar` => NotFound (#98で言われているとおり、ファイルはあるはず)
- `http://localhost:8080/program/board/search.html?foo=bar`  => 200 (なぜかエラーにならないしリダイレクトもされない)
- `http://localhost:8080/program/board/search.html`  => 200 (なぜかエラーにならないしリダイレクトもされない)

`search.html` を正常に配信する基準が見えない。パラメータが正しくセットされていることを見るのであればnameに何が入っていようと検索自体は行えるのだから0件という結果を返すべきだし、
結果が存在しないパラメータを許可しないのであればパラメータが足りていないのにsearch.htmlが配信されているパターンと矛盾する

## 同一timeIDでPOSTした時のレスポンス

```
curl -d "name=a&title=a&text=a&password=a&param=write&timeID=201765111829863000000" localhost:8080/program/board/
```

を何度も実行しても200が返ってくる (データの保存はされていない)
受け付けないのならばエラーを返すべき

**Comment by asada0701** [comment]
- [ ] http://localhost:8080/program/board/search.html?param=search&name= => Bad Request (空文字列で検索した結果を返すべきでは？)
- [ ] http://localhost:8080/program/board/search.html?param=search => Bad Request (まあよい)
- [ ] http://localhost:8080/program/board/search.html?name=a => 200 (なぜかエラーにならないしリダイレクトもされない)
- [ ] http://localhost:8080/program/board/search.html?param=bar => NotFound (#98で言われているとおり、ファイルはあるはず)
- [ ] http://localhost:8080/program/board/search.html?foo=bar => 200 (なぜかエラーにならないしリダイレクトもされない)
- [ ] http://localhost:8080/program/board/search.html => 200 (なぜかエラーにならないしリダイレクトもされない)
- [ ] search.html を正常に配信する基準が見えない。パラメータが正しくセットされていることを見るのであればnameに何が入っていようと検索自体は行えるのだから0件という結果を返すべきだし、
結果が存在しないパラメータを許可しないのであればパラメータが足りていないのにsearch.htmlが配信されているパターンと矛盾する
- [ ] 同一timeIDでPOSTした時のレスポンス
curl -d "name=a&title=a&text=a&password=a&param=write&timeID=201765111829863000000" localhost:8080/program/board/
を何度も実行しても200が返ってくる (データの保存はされていない)
受け付けないのならばエラーを返すべき
